---
- name: Restart firewall
  service: name=firewall state=restarted

# Firewall restart blindly flushes all firewall chains (even DOCKER chains).
# We need to restart docker so it places all its iptables rules back.
# Unfortunately, Ansible does not allow you to define an order of handlers from
# different roles. Only order of handlers from one file is guaranteed - it's the 
# order of their definition.
- name: Restart docker
  service: name=docker state=restarted
  ignore_errors: true
  when: firewall_restart_docker is truthy